/*
 *  Copyright 2019 Anthem Engineering LLC.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package com.anthemengineering.sox.jna;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : sox.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
@SuppressWarnings({"unused", "JavaDoc"})
public class lsx_enum_item extends Structure {
	/**
	 * String name of enumeration.<br>
	 * C type : const char*
	 */
	public Pointer text;
	/** Integer value of enumeration. */
	public int value;
	public lsx_enum_item() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("text", "value");
	}
	/**
	 * @param text String name of enumeration.<br>
	 * C type : const char*<br>
	 * @param value Integer value of enumeration.
	 */
	public lsx_enum_item(Pointer text, int value) {
		super();
		this.text = text;
		this.value = value;
	}
	public lsx_enum_item(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends lsx_enum_item implements Structure.ByReference {
		
	};
	public static class ByValue extends lsx_enum_item implements Structure.ByValue {
		
	};
}
