package com.anthemengineering.sox.jna;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : sox.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class sox_encodings_info_t extends Structure {
	/**
	 * @see sox_encodings_flags_t<br>
	 * < lossy once (lossy1), lossy twice (lossy2), or lossless (none).<br>
	 * C type : sox_encodings_flags_t
	 */
	public int flags;
	/**
	 * < encoding name.<br>
	 * C type : const char*
	 */
	public Pointer name;
	/**
	 * < encoding description.<br>
	 * C type : const char*
	 */
	public Pointer desc;
	public sox_encodings_info_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("flags", "name", "desc");
	}
	/**
	 * @param flags @see sox_encodings_flags_t<br>
	 * < lossy once (lossy1), lossy twice (lossy2), or lossless (none).<br>
	 * C type : sox_encodings_flags_t<br>
	 * @param name < encoding name.<br>
	 * C type : const char*<br>
	 * @param desc < encoding description.<br>
	 * C type : const char*
	 */
	public sox_encodings_info_t(int flags, Pointer name, Pointer desc) {
		super();
		this.flags = flags;
		this.name = name;
		this.desc = desc;
	}
	public sox_encodings_info_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends sox_encodings_info_t implements Structure.ByReference {
		
	};
	public static class ByValue extends sox_encodings_info_t implements Structure.ByValue {
		
	};
}
