package com.anthemengineering.sox.jna;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : sox.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class sox_loopinfo_t extends Structure {
	/**
	 * < first sample<br>
	 * C type : sox_uint64_t
	 */
	public long start;
	/**
	 * < length<br>
	 * C type : sox_uint64_t
	 */
	public long length;
	/** < number of repeats, 0=forever */
	public int count;
	/** < 0=no, 1=forward, 2=forward/back (see sox_loop_* for valid values). */
	public byte type;
	public sox_loopinfo_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("start", "length", "count", "type");
	}
	/**
	 * @param start < first sample<br>
	 * C type : sox_uint64_t<br>
	 * @param length < length<br>
	 * C type : sox_uint64_t<br>
	 * @param count < number of repeats, 0=forever<br>
	 * @param type < 0=no, 1=forward, 2=forward/back (see sox_loop_* for valid values).
	 */
	public sox_loopinfo_t(long start, long length, int count, byte type) {
		super();
		this.start = start;
		this.length = length;
		this.count = count;
		this.type = type;
	}
	public sox_loopinfo_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends sox_loopinfo_t implements Structure.ByReference {
		
	};
	public static class ByValue extends sox_loopinfo_t implements Structure.ByValue {
		
	};
}
